config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  get 'comments/create'

  resources :users
  resources :attendings
  resources :comments
  resources :events
  resources :sessions

  root 'sessions#new'

end

app/models/attending.rb
class Attending < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  validates :name, :location, :state, :event_date, presence: true
  validate :event_date_cannot_be_in_the_past

  has_many :comments, :dependent => :delete_all
  has_many :attendings, :dependent => :delete_all
  has_many :users, through: :attendings
  #has_many :attendees, through: :attendings, :foreign_key => 'user_id', :source =>'user'
  def event_date_cannot_be_in_the_past
    if event_date.present? && event_date < Date.today
      errors.add(:event_date, "can't be in the past")
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name, :last_name, :email, :location, :state, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
  validates :password, length: { minimum: 8 }, allow_nil: true

  has_many :events, :dependent => :delete_all
  has_many :comments, :dependent => :delete_all
  has_many :attendings, :dependent => :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_login
  redirect_to new_session_path if session[:user_id] == nil
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def states
    State.all()
  end

  helper_method :current_user, :states

end

app/controllers/attendings_controller.rb
class AttendingsController < ApplicationController
  def create
    attending = Attending.new(attend_params)

    if attending.save()
      redirect_to events_path
    else
      flash[:errors] = attending.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    attending = Attending.find(params[:id])
    attending.destroy()

    redirect_to events_path
  end

  private
  def attend_params
    params.require(:attend).permit(:event_id, :user_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment  = Comment.new(comment_params)

    if comment.save()
      redirect_to event_path(comment.event)
    else
      flash[:errors] = comment.errors.full_messages
      redirect_to :back
    end

  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :event_id, :user_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login

  def index
    @all_events_in_state = Event.where(state:current_user.state)
    @all_events_out_state = Event.where.not(state:current_user.state)
    #@event = Event.new

    if flash[:name] == nil
      flash[:name] = ""
      flash[:date] = Date.parse(Time.now.to_s)
      flash[:location] = ""
      flash[:state] = "TX"
    end
  end

  def create
    event  = Event.new(event_params)
    event.user = current_user

    if event.save()
      redirect_to events_path
    else
      flash[:errors] = event.errors.full_messages

      flash[:name] = event_params[:name]
      flash[:date] = Date.parse(event_params[:event_date])
      flash[:location] = event_params[:location]
      flash[:state] = event_params[:state]

      redirect_to events_path
    end
  end

  def new
  end

  def edit
  end

  def show
    @event = Event.find(params[:id])
  end

  def update
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy()

    redirect_to events_path

  end

  private
  def event_params
    params.require(:event).permit(:name, :event_date, :location, :state)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])

    if user && user.try(:authenticate, params[:password])
      session[:user_id] = user.id
      redirect_to events_path
    else

      flash[:login_error] = "login"
      flash[:errors] = []

      flash[:login_email] = params[:email]

      if user
        flash[:errors].insert(-1, "Invalid Password")
      else
        flash[:errors].insert(-1, "User not found")
      end

      redirect_to new_session_path
    end
  end

  def new
    if (flash[:first_name] == nil &&
      flash[:login_email] == nil &&
      flash[:last_name] == nil &&
      flash[:email] == nil &&
      flash[:location] == nil &&
      flash[:state] == nil)

      flash[:login_email] = ""
      flash[:first_name] = ""
      flash[:last_name] = ""
      flash[:email] = ""
      flash[:location] = ""
      flash[:state] = "TX"
    end

  end

  def destroy
    session[params[:id]] = nil
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
    user  = User.new(user_params)

    if user.save()
      session[:user_id] = user.id
      redirect_to events_path
    else
      flash[:login_error] = "registration"
      flash[:errors] = user.errors.full_messages

      flash[:first_name] = user_params[:first_name]
      flash[:last_name] = user_params[:last_name]
      flash[:email] = user_params[:email]
      flash[:location] = user_params[:location]
      flash[:state] = user_params[:state]

      redirect_to new_session_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])

    if user.update(user_update_params)
      redirect_to events_path
    else
      flash[:errors] = user.errors.full_messages
      redirect_to edit_user_path
    end
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :location, :state,  :password, :password_confirmation)
  end

  def user_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :location, :state)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendings_helper.rb
module AttendingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendings/create.html.erb
<h1>Attendings#create</h1>
<p>Find me in app/views/attendings/create.html.erb</p>

app/views/attendings/destroy.html.erb
<h1>Attendings#destroy</h1>
<p>Find me in app/views/attendings/destroy.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/events/_event.html.erb
<form action='/events' method='POST'>
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <label for="event[name]">Name:</label><input type="text" name="event[name]" value=""><br>
    <label for="event[event_date]">Date:</label><input type="date" name="event[event_date]" value=""><br>
    <label for="event[location]">Location:</label><input type="text" name="event[location]" value=""><br>
    <label for="event[state]">State:</label>
    <select name="event[state]">
    	<option value="AL">Alabama</option>
    	<option value="AK">Alaska</option>
    	<option value="AZ">Arizona</option>
    	<option value="AR">Arkansas</option>
    	<option value="CA">California</option>
    	<option value="CO">Colorado</option>
    	<option value="CT">Connecticut</option>
    	<option value="DE">Delaware</option>
    	<option value="DC">District Of Columbia</option>
    	<option value="FL">Florida</option>
    	<option value="GA">Georgia</option>
    	<option value="HI">Hawaii</option>
    	<option value="ID">Idaho</option>
    	<option value="IL">Illinois</option>
    	<option value="IN">Indiana</option>
    	<option value="IA">Iowa</option>
    	<option value="KS">Kansas</option>
    	<option value="KY">Kentucky</option>
    	<option value="LA">Louisiana</option>
    	<option value="ME">Maine</option>
    	<option value="MD">Maryland</option>
    	<option value="MA">Massachusetts</option>
    	<option value="MI">Michigan</option>
    	<option value="MN">Minnesota</option>
    	<option value="MS">Mississippi</option>
    	<option value="MO">Missouri</option>
    	<option value="MT">Montana</option>
    	<option value="NE">Nebraska</option>
    	<option value="NV">Nevada</option>
    	<option value="NH">New Hampshire</option>
    	<option value="NJ">New Jersey</option>
    	<option value="NM">New Mexico</option>
    	<option value="NY">New York</option>
    	<option value="NC">North Carolina</option>
    	<option value="ND">North Dakota</option>
    	<option value="OH">Ohio</option>
    	<option value="OK">Oklahoma</option>
    	<option value="OR">Oregon</option>
    	<option value="PA">Pennsylvania</option>
    	<option value="RI">Rhode Island</option>
    	<option value="SC">South Carolina</option>
    	<option value="SD">South Dakota</option>
    	<option value="TN">Tennessee</option>
    	<option value="TX">Texas</option>
    	<option value="UT">Utah</option>
    	<option value="VT">Vermont</option>
    	<option value="VA">Virginia</option>
    	<option value="WA">Washington</option>
    	<option value="WV">West Virginia</option>
    	<option value="WI">Wisconsin</option>
    	<option value="WY">Wyoming</option>
    </select>	<br>

    <input type="submit" value="Add Event" class="buttons">
</form>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div id="header_1">
  <% if current_user %>
    <p>Welcome, <%= current_user.first_name %> <%= current_user.last_name %></p>
  <% end %>
</div>

<div id="header_2">
  <% if current_user %>
    <%= link_to "Edit My Profile", edit_user_path(current_user) %>
    <%= link_to "Logout", session_path(current_user), :method => :delete %>
  <% end %>
</div>
<br>
<br>

<h3>Here are some of the events in your state</h3>

<table>
    <thead>
        <th>Name</th>
        <th>Date</th>
        <th>Location</th>
        <th>Host</th>
        <th>Action/Status</th>
    </thead>
    <% @all_events_in_state.each do |event| %>
    <tr>
        <td><%= link_to event.name, event_path(event) %>
        <td><%= event.event_date %></td>
        <td><%= event.location %></td>
        <td><%= event.user.first_name %></td>
        <td>

          <% if event.user == current_user %>
              <%= link_to "Edit", event_path(event) %>
              <%= link_to "Delete" , event_path(event), :method => :delete  %>
              |
          <% end %>
          <% if event.attendings.find_by(user_id:current_user) %>
              Joining <%= link_to "Cancel", attending_path(event.attendings.find_by(user_id:current_user)), :method => :delete  %>
          <% else %>
            <%= link_to "Join", attendings_path(:attend => {:event_id => event.id, :user_id =>current_user.id}), :method => :post %>
          <% end %>

        </td>
      </tr>
    <% end %>
</table>

<br>

<h3>Here are some of the events in other states</h3>

<table>
    <thead>
        <th>Name</th>
        <th>Date</th>
        <th>Location</th>
        <th>Host</th>
        <th>Action/Status</th>
    </thead>
    <% @all_events_out_state.each do |event| %>
    <tr>
        <td><%= link_to event.name, event_path(event) %></td>
        <td><%= event.event_date %></td>
        <td><%= event.location %></td>
        <td><%= event.user.first_name %></td>
        <td>
          <% if event.user == current_user %>
              <%= link_to "Edit", event_path(event) %>
              <%= link_to "Delete" , event_path(event), :method => :delete  %>
              |
          <% end %>

          <% if event.attendings.find_by(user_id:current_user) %>
              Joining <%= link_to "Cancel", attending_path(event.attendings.find_by(user_id:current_user)), :method => :delete  %>
          <% else %>
            <%= link_to "Join", attendings_path(:attend => {:event_id => event.id, :user_id =>current_user.id}), :method => :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
</table>
<br>

<h3>Add Event</h3>
<form action='/events' method='POST'>
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <label for="event[name]">Name:</label><input type="text" name="event[name]" value="<%=flash[:name]%>"><br>
    <label for="event[event_date]">Date:</label><input type="date" name="event[event_date]" value="<%=flash[:date]%>"><br>
    <label for="event[location]">Location:</label><input type="text" name="event[location]" value="<%=flash[:location]%>"><br>
    <label for="event[state]">State:</label>
    <select name="event[state]">
    <% states.each do |state| %>
      <% if state.state == flash[:state] %>
        <option value ="<%=state.state%>" selected="selected"><%=state.state%></option>
      <% else %>
        <option value ="<%=state.state%>"><%=state.state%></option>
      <% end %>
    <% end %>
    </select>
    <br>

    <input type="submit" value="Add Event" class="buttons">
</form>

<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <p> <%= msg %></p>
  <% end %>
<% end %>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<div id="header_1">
  <% if current_user %>
    <p>Welcome, <%= current_user.first_name %> <%= current_user.last_name %></p>
  <% end %>
</div>

<div id="header_2">
  <% if current_user %>
    <%= link_to "Event Dashboard", events_path %>
    <%= link_to "Logout", session_path(current_user), :method => :delete %>
  <% end %>
</div>

<p><%= @event.name %>
<p>Host: <%= @event.user.first_name %> <%= @event.user.last_name %> </p>
<p>Date: <%= @event.event_date %> </p>
<p>Location: <%= @event.location %> </p>

<p>People who are joining the event: <%= @event.attendings.count %>

<table>
  <thead>
      <th>Name</th>
      <th>Location</th>
      <th>State</th>
  </thead>

  <% @event.users.each do |user| %>
  <tr>
      <td><%= user.first_name %> <%=user.last_name %></td>
      <td><%= user.location %></td>
      <td><%= user.state %></td>
  </tr>
  <% end %>
</table>

<br>
<br>

<p>Discussions about this event: </p>
<br>
<% @event.comments.each do |comment| %>
  <p><%= comment.user.first_name %> says: <%= comment.comment %></p>
  <p>----------</p>
<% end %>
<br>

<h3>Add Comment</h3>
<form action='/comments' method='POST'>
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <input name="comment[event_id]" value="<%=@event.id%>" type="hidden">
    <input name="comment[user_id]" value="<%=current_user.id%>" type="hidden">

    <label for="comment[comment]">Name:</label><input type="text" name="comment[comment]" value=""><br>
    <input type="submit" value="Add Comment" class="buttons">
</form>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeltReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">

      <%= yield %>
  </div>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div id="header_1">
</div>

<div id="header_2">
  <% if current_user %>
    <%= link_to "Event Dashboard", events_path %>
    <%= link_to "Logout", session_path(current_user), :method => :delete %>
  <% end %>
</div>

<br>
<br>


<form action='/users/<%=@user.id%>' method='POST'>
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <input type='hidden' name='_method' value='PUT'>
  <label for="user[first_name]">First Name:</label><input type="text" name="user[first_name]" value="<%= @user.first_name%>"><br>
  <label for="user[last_name]">Last Name:</label><input type="text" name="user[last_name]" value="<%= @user.last_name%>"><br>
  <label for="user[email]">Email:</label><input type="text" name="user[email]" value="<%= @user.email %>"><br>
  <label for="user[location]">Location:</label><input type="text" name="user[location]" value="<%= @user.location %>"><br>
  <label for="user[state]">State:</label>

  <select name="user[state]">
  <% states.each do |state| %>
    <% if @user.state == state.state %>
      <option value ="<%=state.state%>" selected="selected"><%=state.state%></option>
    <% else %>
      <option value ="<%=state.state%>"><%=state.state%></option>
    <% end %>
  <% end %>
  </select>
  <br>

  <input type="submit" value="Update" class="buttons">
</form>

<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <p> <%= msg %></p>
  <% end %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>